# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: 1.0.$(Rev:.r)

trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  project: '**/ObservceServices.Core.csproj'
  testProjects: '**/*[Tt]ests/*.csproj'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(project)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(project)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  enabled: false
  inputs:
    command: test
    projects: '$(testProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(project)'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True
    workingDirectory: src/

- task: DotNetCoreCLI@2
  displayName: Publish3
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(project)'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True
    workingDirectory: src/

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    nobuild: true
    includesymbols: true
    versioningScheme: byBuildNumber

- task: NuGetCommand@2
  displayName: 'NuGet push to nuget'
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'Nuget push'
  continueOnError: true